### ISSUE TITLE
Is it possible to use new qbittorrent version.

### ISSUE THREAD

**Issue by leonard4546** [ap-pauloafonso/ratio-spoof#15]
As the title says is it possible to add support for new version? Like 4.2.5 or 4.3.+ etc.
Thanks for this project.

**Comment by ap-pauloafonso** [comment]
Yes, it's definitely possible, my plan is to have another optional flag that we can choose the client emulation, (for example: -c qbittorrent-v123). 
Thanks for reaching out, once i get some free time i will work on that ;)

**Comment by leonard4546** [comment]
> Yes, it's definitely possible, my plan is to have another optional flag that we can choose the client emulation, (for example: -c qbittorrent-v123).
> Thanks for reaching out, once i get some free time i will work on that ;)

Thanks for considering my request.

**Comment by leonard4546** [comment]
.

**Comment by ap-pauloafonso** [comment]
@leonard4546, i'm working on a new version, would you want to test it?

**Comment by leonard4546** [comment]
@ap-pauloafonso Thanks it's working perfectly.
