### ISSUE TITLE
Parece não funcionar 

### ISSUE THREAD

**Issue by ronioncloud** [ap-pauloafonso/ratio-spoof#2]
Testei no Semeandocc e não obtive sucesso. ;/

**Comment by ronioncloud** [comment]
Parece ser a versão do python errada, tem algum requerimento que precisa instalar?

**Comment by ap-pauloafonso** [comment]
Como uma versao recente de python3 instalada era para funcionar sem problemas, poderia mostrar o erro que está acontecendo?

**Comment by ronioncloud** [comment]
Obrigado pela breve resposta :) Funcionou no windows \o

No meu VPS usando ubuntu. tive alguns problemas,  foi que ao executar o script ele rollava a página para a primeira linha (como se eu estivesse pressionando a tecla home constantemente) tendo, adicionado muitas linhas abaixo. (se eu rolava para baixo, ele voltava ao topo, alem de gerar várias linhas)

**Comment by ronioncloud** [comment]
Outra dúvida, tem como adicionar mais de um arquivo .torrent no mesmo commando? ou devo rodar várias instâncias? Parabéns pelo trabalho :D

**Comment by ap-pauloafonso** [comment]
Valeu @ronioncloud , sobre adicionar outros .torrent no mesmo comando não tem como atualmente, quando fiz essa ferramenta a ideia era ter algo simples que fosse facil de usar com comando de linha. Caso realmente precise é possivel executar N comandos em paralelo porem eu não recomendo fazer isso se o tracker for inteligente.

**Comment by ronioncloud** [comment]
Parece que o BJ usa outra técnica, não aparece os downloads lá ;x Testou nele? abraço mestre

**Comment by ronioncloud** [comment]
@ap-pauloafonso você chegou a testar no bj?

**Comment by ap-pauloafonso** [comment]
@ronioncloud Como eu não tenho conta no bj, não foi testado, poderia mostrar o erro? a menos que eles usem UDP para anúncios no tracker, nesse caso não funcionaria mesmo na implementação atual que é para trackers do tipo HTTP/s

**Comment by ronioncloud** [comment]
@ap-pauloafonso não acontece nenhum erro. Aguardei o período para o anúncio. As não mudou nada no site. Também não consta na lista dos downloads do site. ;x

**Comment by ap-pauloafonso** [comment]
@ronioncloud sem um arquivo .torrent fica difícil de eu debugar, quer me enviar um arquivo no meu email? ap.pauloafonso@gmail.com
