### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by Triramama** [ap-pauloafonso/ratio-spoof#27]
I inserted this line in the cmd:

>ratio-spoof -d 2gb -ds 500kbps -u 1gb -us 1024kbps -t "torrentfile_path"

It looks like it works
But the interval at which it sends "announcements" is 1 hour long, not 30s like in the tutorial what could be the cause of this?

**Comment by heypious** [comment]
The announcement interval is set by your tracker and not your client.

**Comment by ap-pauloafonso** [comment]
yep, the reason why its showing 30s on the demo, is because i overwrote the tracker interval amount just for the sake of demonstration.
