### ISSUE TITLE
Avoid else in the flag.Usage

### ISSUE THREAD

**Issue by damianopetrungaro** [ap-pauloafonso/ratio-spoof#4]
When using a custom function for the [`flag.Usage()`](https://github.com/ap-pauloafonso/ratio-spoof/blob/144c8adf3c66add7cc0c050c7a3807a8583a75f8/cmd/main.go#L26) definition
we may simplify the code!

BEFORE
```go
flag.Usage = func() {
		var osExecutableSuffix string
		if runtime.GOOS == "windows" {
			fmt.Println(`usage: 
	ratio-spoof.exe -t <TORRENT_PATH> -d <INITIAL_DOWNLOADED> -ds <DOWNLOAD_SPEED> -u <INITIAL_UPLOADED> -us <UPLOAD_SPEED>`, osExecutableSuffix)
		} else {
			fmt.Println(`usage: 
	./ratio-spoof -t <TORRENT_PATH> -d <INITIAL_DOWNLOADED> -ds <DOWNLOAD_SPEED> -u <INITIAL_UPLOADED> -us <UPLOAD_SPEED>`, osExecutableSuffix)
		}
    ...
```

AFTER
```go
flag.Usage = func() {
    fmt.Printf(`usage: %s -t <TORRENT_PATH> -d <INITIAL_DOWNLOADED> -ds <DOWNLOAD_SPEED> -u 
    <INITIAL_UPLOADED> -us <UPLOAD_SPEED>\n`, os.Args[0])
    ...
    
```

### What is os.Args?
[`os.Args`](https://github.com/golang/go/blob/ba76567bc2500204432ed8a5cb28848410e74447/src/os/proc.go#L16) is a package-level exported variable (meaning that it gets initialized once the binary stars) which gets filled from an [`init`](https://github.com/golang/go/blob/ba76567bc2500204432ed8a5cb28848410e74447/src/os/proc.go#L18) function from the os package; this variable contains at the first index the binary path, at the next indexes you _may_ find arguments and flags, if passed when executing the binary.

### What is happening behind the scene?
When the [`init`](https://github.com/golang/go/blob/ba76567bc2500204432ed8a5cb28848410e74447/src/os/proc.go#L18) function [gets called](https://golang.org/doc/effective_go.html#init), depending on which os the binary is running, it may call
the one defined in the [exec_windows.](https://github.com/golang/go/blob/ba76567bc2500204432ed8a5cb28848410e74447/src/os/exec_windows.go#L100) or use a [compiler directive](https://golang.org/cmd/compile/#hdr-Compiler_Directives) from the proc.go file itself.

From the go doc about it:
```
//go:linkname localname [importpath.name]

This special directive does not apply to the Go code that follows it. Instead, the //go:linkname directive instructs the compiler to use “importpath.name” as the object file symbol name for the variable or function declared as “localname” in the source code. If the “importpath.name” argument is omitted, the directive uses the symbol's default object file symbol name and only has the effect of making the symbol accessible to other packages. Because this directive can subvert the type system and package modularity, it is only enabled in files that have imported "unsafe". 
```

The compiler directive will use the one defined [here](https://github.com/golang/go/blob/ba76567bc2500204432ed8a5cb28848410e74447/src/runtime/runtime.go#L59)

A bit of compiler+runtime magic here :D Hope this is a bit more clear 💪

**Comment by ap-pauloafonso** [comment]
Nice call, definitely more elegant. Thank you for the detailed explanation ;)
