### ISSUE TITLE
What about simplifying the qbitTorrent?

### ISSUE THREAD

**Issue by damianopetrungaro** [ap-pauloafonso/ratio-spoof#7]
I'd have simplified this in [this](https://github.com/ap-pauloafonso/ratio-spoof/blob/1ab6b86dd2c781ade09e75cb40dbb6911806c39f/emulation/qbittorrent.go) way:
(let me know if you can't simplify it in this way since I don't know the behavior of this qbitTorrent)

```go
func init() {
	rand.Seed(time.Now().UnixNano())
}

type QbitTorrent struct {
	Name        string
	Query       string
	Headers map[string]string
	Key         string
	PeerID      string
}

func NewQbitTorrent() *QbitTorrent { // or return an interface if you want to keep `qbitTorrent` this unexported
	return &QbitTorrent{
		Name:            name,
		Query:           query,
		Headers:     map[string]string{"User-Agent": "qBittorrent/4.0.3", "Accept-Encoding": "gzip"},
		Key:             strings.ToUpper(randomString(4)),
		PeerID:          fmt.Sprintf("-qB4030-%s", randomString(12)),
	}
}
...
func randomString(n int) string {
    randomBytes := make([]byte, n)
    rand.Read(randomBytes)
    return hex.EncodeToString(randomBytes)
}
```

the `func init`, as explained in the other issue, get called once per package after the variables have been initialized and the `rand.Seed` will initialize the default `rand.Source` to a deterministic state (you can safely do it one per package).

Also, I would consider making the fields of the `QbitTorrent` exported since the "making all the field non-exported and provide getter/setter" comes from an OOP world, wherein Go would make it a bit "harder" to maintain.
*BUT* if you think that this is needed because you want to make 100% no one will change those values (for any reason) then you can add back the method to the method.

**Comment by ap-pauloafonso** [comment]
Oh i like the idea of using init, so the qbit package does not deppend of outside seed right?

As for using structs, i think for this project would be better using methods because of the future emulation implementations that the user could choose from, for example;
- emulation/qbittorrent (as is)
- emulation/utorrent (future)
- emulation/deluge (future)

What do you think ? Thanks again ;)

**Comment by damianopetrungaro** [comment]
Then you may have an interface named `Emultation` (maybe a better name is possible), and all the N factory functions will return and the interface and all the implementation are not exported.

What do you think?

**Comment by ap-pauloafonso** [comment]
I already have a interface on the file who uses it (ratio-spoof.go), but i think i should rename it to a better name like Torrent ClientEmulation

```go
type TorrentClient interface {
	PeerID() string
	Key() string
	Query() string
	Name() string
	Headers() map[string]string
	NextAmountReport(DownloadCandidateNextAmount, UploadCandidateNextAmount, leftCandidateNextAmount, pieceSize int) (downloaded, uploaded, left int)
}
```

The factory idea seems really nice, i look foward to implementing that.
As always thank you very much ;)
