### ISSUE TITLE
Why not returning an error here?

### ISSUE THREAD

**Issue by damianopetrungaro** [ap-pauloafonso/ratio-spoof#8]
https://github.com/ap-pauloafonso/ratio-spoof/blob/1ab6b86dd2c781ade09e75cb40dbb6911806c39f/ratiospoof/ratiospoof.go#L401

**Comment by ap-pauloafonso** [comment]
yes, there are other places that i was triggering panic for no reason, a couple days ago i fixed these cases, now we always return the error to the caller.
